tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#c8c6c6",
        "on-tertiary-container": "#848483",
        "on-error": "#ffffff",
        "secondary-container": "#e0dfe4",
        "surface-bright": "#faf9fe",
        "tertiary-fixed": "#e4e2e1",
        surface: "#faf9fe",
        "on-surface": "#1a1b1f",
        "primary-fixed": "#e3e2e9",
        "on-secondary-fixed": "#1a1b1f",
        "on-background": "#1a1b1f",
        "on-primary-container": "#83838a",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#e3e2e7",
        "outline-variant": "#c7c6cb",
        "on-primary-fixed-variant": "#46464c",
        "inverse-on-surface": "#f1f0f5",
        "on-tertiary": "#ffffff",
        tertiary: "#000000",
        "surface-container-high": "#e9e7ed",
        primary: "#000000",
        "inverse-primary": "#c7c6cd",
        "tertiary-container": "#1b1c1c",
        background: "#faf9fe",
        "on-secondary-container": "#626267",
        "secondary-fixed": "#e3e2e7",
        "on-tertiary-fixed-variant": "#474747",
        "on-tertiary-fixed": "#1b1c1c",
        "on-primary": "#ffffff",
        "surface-dim": "#dad9de",
        "primary-fixed-dim": "#c7c6cd",
        outline: "#77767b",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#1a1b20",
        "secondary-fixed-dim": "#c7c6cb",
        "on-secondary": "#ffffff",
        "surface-container-low": "#f4f3f8",
        "primary-container": "#1a1b20",
        "surface-variant": "#e3e2e7",
        "inverse-surface": "#2f3034",
        "on-surface-variant": "#46464b",
        "surface-tint": "#5e5e64",
        "on-secondary-fixed-variant": "#46464b",
        "on-error-container": "#93000a",
        "surface-container": "#eeedf2",
        secondary: "#5e5e62",
        error: "#ba1a1a",
      },
      fontFamily: {
        headline: ["Space Grotesk"],
        body: ["Inter"],
        label: ["Inter"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
};
